small change in Makefile.in in zipscript/src - use install instf rm & cp on make install, always +s on ng-chown

diff --git a/trunk/zipscript/src/Makefile.in b/trunk/zipscript/src/Makefile.in
--- a/trunk/zipscript/src/Makefile.in
+++ b/trunk/zipscript/src/Makefile.in
@@ -66,8 +66,19 @@ install:
 	chown 0:0 $(prefix)$(storage)
 	chmod 4777 $(prefix)$(storage)
 	if [ -e $(prefix)$(datapath)/logs/glftpd.log ]; then chmod 666 $(prefix)$(datapath)/logs/glftpd.log; fi
-	if [ -e $(bindir) ]; then (cd $(bindir) && rm -f zipscript-c postdel racestats cleanup datacleaner rescan ng-undupe ng-chown audiosort); cp -f zipscript-c postdel racestats cleanup datacleaner rescan ng-undupe ng-chown audiosort $(bindir)/; fi
+	if [ ! -e $(bindir) ]; then exit 1; fi
+	install -m0755 zipscript-c $(bindir)
+	install -m0755 postdel $(bindir)
+	install -m0755 racestats $(bindir)
+	install -m0755 cleanup $(bindir)
+	install -m0755 datacleaner $(bindir)
+	install -m0755 rescan $(bindir)
+	install -m0755 ng-undupe $(bindir)
+	install -m0755 audiosort $(bindir)
+	install -m4755 ng-chown $(bindir)
+#	if [ -e $(bindir) ]; then (cd $(bindir) && rm -f zipscript-c postdel racestats cleanup datacleaner rescan ng-undupe ng-chown audiosort); cp -f zipscript-c postdel racestats cleanup datacleaner rescan ng-undupe ng-chown audiosort $(bindir)/; fi
 	if [ -d "$(prefix)$(datapath)/misc" ] && [ ! -e "$(prefix)$(datapath)/misc/banned_filelist.txt" ]; then cp -f banned_filelist.txt $(prefix)$(datapath)/misc/; fi
+#	if [ -e $(bindir)/ng-chown ]; then chmod +s $(bindir)/ng-chown; fi
 
 distclean: clean
 
